export { default as home } from './Home.svg?raw';
export { default as task } from './Task.svg?raw';
export { default as taskAlt } from './TaskAlt.svg?raw';
export { default as calendar } from './Calendar.svg?raw';
export { default as cog } from './Cog.svg?raw';
export { default as chart } from './Chart.svg?raw';
export { default as book } from './Book.svg?raw';
export { default as bookAlt } from './BookAlt.svg?raw';
export { default as note } from './Note.svg?raw';
export { default as noteAlt } from './NoteAlt.svg?raw';
export { default as dark } from './Dark.svg?raw';
export { default as light } from './Light.svg?raw';
export { default as creditCard } from './CreditCard.svg?raw';
export { default as bell } from './Bell.svg?raw';
export { default as hamburger } from './Hamburger.svg?raw';
export { default as user } from './User.svg?raw';
export { default as trash } from './Trash.svg?raw';
export { default as check } from './Check.svg?raw';
export { default as close } from './Close.svg?raw';
export { default as help } from './Help.svg?raw';
export { default as folder } from './Folder.svg?raw';
export { default as trophy } from './Trophy.svg?raw';
export { default as diploma } from './Diploma.svg?raw';
export { default as cap } from './Cap.svg?raw';
// export { default as close } from './Close.svg?raw';
// export { default as checkO } from './CheckO.svg?raw';
// export { default as ellipsisV } from './EllipsisV.svg?raw';
// export { default as bolt } from './Bolt.svg?raw';
// export { default as plus } from './Plus.svg?raw';
// export { default as image } from './Image.svg?raw';
export { default as clock } from './Clock.svg?raw';
// export { default as lock } from './Lock.svg?raw';
